version: '2'

services:
    ss: 
        build:
            context: ./shadowsocks-server
            args:
                # your shadowsocks password
                - PASSWORD=
                # your shadowsocks port
                - PORT=8388
        ports:
            - "8388:8388"
